git-tag-changelog: general refactor with better support for prefixes in commit messages
  @ 04:10 hs

diff --git a/git-tag-changelog b/git-tag-changelog
--- a/git-tag-changelog
+++ b/git-tag-changelog
@@ -79,44 +79,187 @@ EOF
 exit 0
 }
 
-[[ "$1" =~ ^[-]+(h|help) ]] && usage
+function subject_del_issue()
+{
+  echo "$1" \
+    | sed "s/\(REL\|FIX\) \#[0-9]\+ //g" \
+    | sed 's/^ \+\-//g; s/^\- //g'
+}
 
-[[ -d '.git'             ]] || die "NOT FOUND VALID GIT REPOSITORY"
-[[ -e '.changelog'       ]] && source .changelog
+function git_log_subject()
+{
+  local ISSUE SHASH SUBJECT
 
-[[ -n "$CHANGELOG"       ]] || CHANGELOG='CHANGELOG.md'
-[[ -z "$1"               ]] || CHANGELOG="$1"
-[[ -n "$DATE_REGEX"      ]] || DATE_REGEX='^[0-9]{4}-[0-9]{2}-[0-9]{2}'
-[[ -n "$NAME"            ]] || NAME="$(echo "$PWD" | rev | cut -d/ -f1 | rev)"
-[[ -n "$TITLE"           ]] || TITLE="${NAME^^} CHANGELOG"
-[[ -n "$SEMVER"          ]] || SEMVER='[Semantic Versioning](https://semver.org/spec/v2.0.0.html)'
-[[ -n "$REPO_URL"        ]] || REPO_URL="$(git-remote-geturl)"
-[[ -n "$IGNORE_REGEX"    ]] || IGNORE_REGEX='Merge (branch|tag)'
+  SHASH="$1"
+  SUBJECT="$(subject_del_issue "$2")"
+  ISSUE="$(git-commit-getissue "$SHASH")"
+  ISSUE="${ISSUE%% *}"
 
-TAGS="$(mktemp)"
-TMP="$(mktemp)"
-LOG="$(mktemp)"
+  if [[ -z "$ISSUE" ]]
+  then
+    printf "%s %s\\n"    '-' "$SUBJECT"
+  else
+    printf "%s %s %s\\n" '-' "$ISSUE" "$SUBJECT"
+  fi
+}
+
+function params()
+{
+
+  [[ "$1" =~ ^[-]+(h|help)   ]] && usage
+
+  [[ -d '.git'               ]] || die "NOT FOUND VALID GIT REPOSITORY"
+  [[ -e '.changelog'         ]] && source .changelog
+
+  [[ -n "$CHANGELOG"         ]] || CHANGELOG='CHANGELOG.md'
+  [[ -z "$1"                 ]] || CHANGELOG="$1"
+
+}
+
+function defaults()
+{
+
+  [[ -n "$DATE_REGEX"        ]] || DATE_REGEX='^[0-9]{4}-[0-9]{2}-[0-9]{2}'
+  [[ -n "$NAME"              ]] || NAME="$(echo "$PWD" | rev | cut -d/ -f1 | rev)"
+  [[ -n "$TITLE"             ]] || TITLE="${NAME^^} CHANGELOG"
+  [[ -n "$SEMVER"            ]] || SEMVER='[Semantic Versioning](https://semver.org/spec/v2.0.0.html)'
+  [[ -n "$REPO_URL"          ]] || REPO_URL="$(git-remote-geturl)"
+  [[ -n "$IGNORE_REGEX"      ]] || IGNORE_REGEX='Merge (branch|tag)'
+  [[ -n "$REGEX_TAG_EXCLUDE" ]] || REGEX_TAG_EXCLUDE='REGEX_TAG_EXCLUDE'
+  [[ -n "$REGEX_TAG_VERSION" ]] || REGEX_TAG_VERSION='[0-9]+\.[0-9]+\.[0-9]+'
+  [[ -n "$REGEX_COMMIT"      ]] || REGEX_COMMIT='^[a-f0-9]{6,8}'
+  [[ -n "$REGEX_PREFIX"      ]] || REGEX_PREFIX='[a-zA-Z/\.\-]+:'
+
+}
+
+function temporal()
+{
+  LOG="$(mktemp)"
+  LOG_NO_PREFIX="$(mktemp)"
+  LOG_PREFIX="$(mktemp)"
+  PREFIXES="$(mktemp)"
+  TAGS="$(mktemp)"
+  TMP="$(mktemp)"
+}
+
+function clean()
+{
+  rm -f "$LOG"
+  rm -f "$TMP"
+  rm -f "$TAGS"
+  rm -f "$PREFIXES"
+  rm -f "$LOG_NO_PREFIX"
+  rm -f "$LOG_PREFIX"
+}
+
+function get_log_from_to()
+{
+
+  # get commits log and remove (REL|FIX) #ISSUE1 #ISSUE2 in Subject
+  git log --oneline --pretty --format="%h %s" "$TO"..."$FROM"                    \
+    | sed 's/\(#[0-9]\+\) #[0-9]\+/\1/g; s/\(REL\|FIX\) #[0-9]\+//Ig; s/ \+/ /g' \
+    | sed -r 's/(^[0-9a-f]{6,8}) (\-|:) /\1 /g'                                  \
+    | grep -v Squashed                                                           \
+    | grep -vE "$IGNORE_REGEX"                                                   > "$LOG"
+
+}
+
+function get_log_no_prefix()
+{
+  grep -vE "$REGEX_COMMIT $REGEX_PREFIX" "$LOG" > "$LOG_NO_PREFIX"
+}
+
+function get_log_prefix()
+{
+  grep -E "$REGEX_COMMIT $REGEX_PREFIX" "$LOG" > "$LOG_PREFIX"
+}
+
+function get_commits_no_prefix()
+{
+  while read -r SHASH SUBJECT
+  do
+
+    git_log_subject "$SHASH" "$SUBJECT"
+
+  done < "$LOG_NO_PREFIX" | awk '!seen[$0]++'
+  printf "\\n"
+}
+
+function get_prefixes()
+{
+  grep -E "$REGEX_COMMIT $REGEX_PREFIX" "$LOG_PREFIX" \
+    | awk '{print $2}'                                \
+    | sort -u                                         > "$PREFIXES"
+}
+
+function get_commits_prefix()
+{
+  while read -r PREFIX
+  do
+
+    printf "### \`%s\`\\n\\n" "${PREFIX//:/}"
+
+    grep "$PREFIX" "$LOG_PREFIX" | while read -r SHASH PREFIX SUBJECT
+    do
+
+      git_log_subject "$SHASH" "$SUBJECT"
+
+    done | awk '!seen[$0]++'
+
+    printf "\\n"
+
+  done < "$PREFIXES"
+}
+
+function get_commits_first()
+{
+  git rev-list --max-parents=0 HEAD \
+    | cut -c -7                     > "$TAGS"
+}
+
+function get_tags_from()
+{
+  git tag --sort version:refname    \
+    | grep -vE "$REGEX_TAG_EXCLUDE" \
+    | awk '{print $1}'              >>"$TAGS"
+}
+
+function get_tags_to()
+{
+  tail -n+2 "$TAGS"                 > "$TMP"
+}
+
+function join_tags_from_to()
+{
+  paste "$TAGS" "$TMP" | tac | sponge "$TAGS"
+}
+
+function filter_tags()
+{
+  grep -E "$REGEX_TAG_VERSION" "$TAGS" | sponge "$TAGS"
+}
+
+function get_tags()
+{
+  get_commits_first
+  get_tags_from
+  get_tags_to
+  join_tags_from_to
+  filter_tags
+}
+
+function show_title()
+{
+  printf "# [_%s_](%s)\\n\\n" "$TITLE" "$REPO_URL"
+  [[ -z "$SEMVER" ]] \
+    || printf " - %s\\n" "this project adheres to $SEMVER"
+  printf "\\n"
+}
 
 function changelog_generate()
 {
 
-## first commit
-git rev-list --max-parents=0 HEAD | cut -c -7     > "$TAGS"
-
-## tags column from
-git tag --sort version:refname | awk '{print $1}' >>"$TAGS"
-
-## tags column to
-tail -n+2 "$TAGS" > "$TMP"
-
-## join tags column from and to in cronological order
-paste "$TAGS" "$TMP" | tac | sponge "$TAGS"
-
-## title
-printf "# [_%s_](%s)\\n\\n" "$TITLE" "$REPO_URL"
-## include Semantic Versioning
-[[ -z "$SEMVER" ]] || printf " - %s\\n" "this project adheres to $SEMVER"
-printf "\\n"
+  show_title
 
 while read -r FROM TO
 do
@@ -139,43 +282,30 @@ do
   printf "## [\`%s - %s\`](%s)%s\\n\\n" \
          "$RELEASE" "$DATE" "$TAG_URL" "$TAG_NOTE"
 
-  # get commits log
-  git log --oneline --pretty --format="%s" "$TO"..."$FROM" \
-    | grep -vE "$IGNORE_REGEX"                             > "$LOG"
-
-  if grep -qE '^[a-zA-Z\-]+:' "$LOG" 2>/dev/null
-  then
-
-    # group commits by prefix:
-    awk '{print $1}' "$LOG" | grep ':' | sort -u | while read -r PREFIX
-    do
-
-      printf "### \`%s\`\\n\\n" "${PREFIX//:/}"
-      grep -E "^$PREFIX" "$LOG" \
-        | cut -d ':' -f2- \
-        | sed 's/^/-/g' \
-        | awk '!seen[$0]++'
-      printf "\\n"
-
-    done
-
-  else
-
-    # commits without prefix
-    sed 's/^/- /g' "$LOG" | awk '!seen[$0]++'
-    printf "\\n"
-
-  fi
+  get_log_from_to
+  get_log_no_prefix
+  get_log_prefix
+  get_commits_no_prefix
+  get_prefixes
+  get_commits_prefix
 
 done < "$TAGS"
 
 }
 
-# generate and overwrite CHANGELOG
-changelog_generate | sed '${/^$/d;}' > "$CHANGELOG" \
-  && echo "GENERATE $CHANGELOG"
+function main()
+{
 
-# clean temporal files
-rm -f "$LOG"
-rm -f "$TMP"
-rm -f "$TAGS"
+  temporal
+  defaults
+  params "$@"
+  get_tags
+  # generate and overwrite CHANGELOG
+  changelog_generate \
+    | sed '${/^$/d;}' > "$CHANGELOG" \
+    && echo "GENERATE $CHANGELOG"
+  clean
+
+}
+
+main "$@"
