git-tag-summary: don't include tag link to file when NO_TAG_LINK is enabled
  @ 00:12 hs

diff --git a/git-tag-summary b/git-tag-summary
--- a/git-tag-summary
+++ b/git-tag-summary
@@ -23,18 +23,25 @@ function die()
   exit 0
 }
 
-[[ -n "$BASH_DEBUG" ]] && set -x
-[[ -d ".git"        ]] || die "NOT FOUND .git DIRECTORY"
-[[ -n "$DATE_REGEX" ]] || DATE_REGEX='^[0-9]{4}-[0-9]{2}-[0-9]{2}'
-[[ -n "$TAG_REGEX"  ]] || TAG_REGEX='^v[0-9]+\.[0-9]+\.[0-9]+'
-[[ -n "$TAG_SORT"   ]] || TAG_SORT='-version:refname'
-[[ -n "$TAG_WIDTH"  ]] || TAG_WIDTH='8'
-[[ -n "$DES_WIDTH"  ]] || DES_WIDTH='110'
+[[ -n "$BASH_DEBUG"  ]] && set -x
+[[ -d ".git"         ]] || die "NOT FOUND .git DIRECTORY"
+[[ -n "$DATE_REGEX"  ]] || DATE_REGEX='^[0-9]{4}-[0-9]{2}-[0-9]{2}'
+[[ -n "$TAG_REGEX"   ]] || TAG_REGEX='^v[0-9]+\.[0-9]+\.[0-9]+'
+[[ -n "$TAG_SORT"    ]] || TAG_SORT='-version:refname'
+[[ -n "$TAG_WIDTH"   ]] || TAG_WIDTH='8'
+[[ -n "$DES_WIDTH"   ]] || DES_WIDTH='110'
+[[ -n "$NO_TAG_LINK" ]] || NO_TAG_LINK=0
 
 GIT_URL="$(git-remote-geturl)"
 GIT_DIR="$(echo "$GIT_URL" | rev | cut -d/ -f1 | rev)"
 GIT_WIDTH="$(echo "$GIT_DIR" | wc -L)"
-COL_WIDTH="$((2+TAG_WIDTH+2+1+GIT_WIDTH+1+TAG_WIDTH+3+1))"
+
+if [[ "$NO_TAG_LINK" -eq 1 ]]
+then
+  COL_WIDTH="$((1+TAG_WIDTH+1))"
+else
+  COL_WIDTH="$((2+TAG_WIDTH+2+1+GIT_WIDTH+1+TAG_WIDTH+3+1))"
+fi
 
 printf "| %-10s | %-*s | %-*s |\n" \
        '_date_'                    \
@@ -57,7 +64,13 @@ git tag -n --sort "$TAG_SORT" \
 
       DATE="$(git log -1 --format=%ci "$TAG" | grep -Eo "$DATE_REGEX")"
       FILE="${GIT_DIR}-${TAG}.md"
-      TAG_LINK="$(printf "[\`%*s\`](%s)" "$TAG_WIDTH" "$TAG" "$FILE")"
+
+      if [[ "$NO_TAG_LINK" -eq 1 ]]
+      then
+        TAG_LINK="$(printf "\`%*s\`" "$TAG_WIDTH" "$TAG")"
+      else
+        TAG_LINK="$(printf "[\`%*s\`](%s)" "$TAG_WIDTH" "$TAG" "$FILE")"
+      fi
 
       printf "| %10s | %-*s | %-*s |\n" \
              "$DATE"                    \
